### ISSUE TITLE
Give root access to James

### ISSUE THREAD

**Issue by jamesgeddes** [GeekZoneHQ/minecraft-server#13]
Give @jamesgeddes root access so that he can do #7 and #6

**Comment by CarwynNelson** [comment]
Ah yes. Could we sit down some time this Friday to get this sorted? I can also take that time to show you how to safely install plugins, and maybe we can even make some improvements to that process to make it easier.

**Comment by jamesgeddes** [comment]
Sure thing :smile:

**Comment by jamesgeddes** [comment]
This is now done
